# Generated by Django 5.0.2 on 2024-02-28 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_your_boolean_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('messageId', models.IntegerField(blank=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save', to='message.profil')),
            ],
        ),
    ]
