# Generated by Django 5.0.2 on 2024-02-25 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_contact_sender_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='message.profil')),
            ],
        ),
    ]
