# Generated by Django 5.0.2 on 2024-02-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_savemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='savemessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
