# Generated by Django 5.0.2 on 2024-03-23 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_savemessage_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sendimage',
            name='sender',
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='savemessage',
            name='profil',
        ),
        migrations.RemoveField(
            model_name='sendimage',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AddImage',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
        migrations.DeleteModel(
            name='SaveMessage',
        ),
        migrations.DeleteModel(
            name='SendImage',
        ),
    ]
