# Generated by Django 5.0.2 on 2024-02-25 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_addimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgage', models.ImageField(blank=True, upload_to='')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendImage', to='message.message')),
            ],
        ),
    ]
