# Generated by Django 5.0.2 on 2024-03-23 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_remove_contact_contact_remove_contact_sender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('sendMessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='message.message')),
            ],
        ),
    ]
