# Generated by Django 5.0.2 on 2024-03-22 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_alter_message_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField(blank=True)),
                ('sendMessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='message.message')),
            ],
        ),
    ]
