# Generated by Django 5.0.2 on 2024-03-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_remove_message_message_sendmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmessage',
            name='desc',
        ),
    ]
