# Generated by Django 5.0.2 on 2024-03-23 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_remove_contact_contact_contact_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='savemessage',
            name='messageId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='message.message'),
            preserve_default=False,
        ),
    ]
