# Generated by Django 5.0.2 on 2024-03-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_savemessage_messageid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savemessage',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
