# Generated by Django 5.0.2 on 2024-03-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_alter_savemessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='savemessage',
            name='call',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
